### ISSUE TITLE
Docker构建websocket server的TLS问题

### ISSUE THREAD

**Issue by hdu12** [99percentpeople/weblink#10]
nginx反代https没什么问题，但是会遇到websocket问题
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

对websocket不太熟悉，猜测是docker构建的ws server没有配置wss

希望作者能看一下，谢谢

**Comment by 99percentpeople** [comment]
将VITE_WEBSOCKET_URL=ws://xxxxxx/ws换为wss://xxxxxx/ws就可以了

**Comment by hdu12** [comment]
感谢回复，那我是不是要把ws server的tls给开起来，我改了docker compose不知道是不是正确

  ws-server:
    build:
      context: https://github.com/99percentpeople/weblink-ws-server.git
    environment:
      - LOG_LEVEL=info
      - TLS_CERT_FILE=/usr/ssl/cert.pem
      - TLS_KEY_FILE=/usr/ssl/key.pem
    volumes:
      - /docker/weblink-public/docker/ssl:/usr/ssl
    ports:
      - "9000:9000"
目前报错是变了，变成了WebSocket error occurred

**Comment by 99percentpeople** [comment]
对了忘记说了，如果是wss的话检查你端口是不是443，如果原来是ws://xxx:8080/ws，请改为wss://xxx:443/ws，如果原来浏览器打开过这个页面，请在设置页面重置ws服务链接
