### ISSUE TITLE
错误报告，续bilibili视频

### ISSUE THREAD

**Issue by chengwy2014** [99percentpeople/weblink#3]
![IMG_4946](https://github.com/user-attachments/assets/b9645318-e493-4916-9411-e8ff7cdc3874)

**Comment by dudushsh2014** [comment]
![IMG_4946](https://github.com/user-attachments/assets/53985105-6f26-462f-b1ea-3c8ea04fbb8c)

**Comment by chengwy2014** [comment]
这是图片链接：https://private-user-images.githubusercontent.com/159882578/380488498-b9645318-e493-4916-9411-e8ff7cdc3874.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjY3NTIsIm5iZiI6MTczMDAyNjQ1MiwicGF0aCI6Ii8xNTk4ODI1NzgvMzgwNDg4NDk4LWI5NjQ1MzE4LWU0OTMtNDkxNi05NDExLWU4ZmY3Y2RjMzg3NC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjdUMTA1NDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjYwN2JhNTNlZjlhMjY0MGQxZjcxY2EzMDE5Njk1NmJlMDIxNmNhNzQ4ODZmZGE4YzE5YTMxNWNlMmNhMWQ5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NOHyxMKAwCnf8E901--_kxX4TwFXFyO82jE99Idt9AM

**Comment by 99percentpeople** [comment]
@dudushsh2014 浏览器不支持web crypto API，请换一个浏览器重试，可以使用Chrome或者edge的最新版
