### ISSUE TITLE
在本地启动如果指定host,报错无法使用

### ISSUE THREAD

**Issue by dongfangbai-a** [99percentpeople/weblink#5]
![image](https://github.com/user-attachments/assets/a6472903-2edb-4175-b46b-14877545bd64)
![image](https://github.com/user-attachments/assets/6b588557-f23a-4617-82d6-ac85c32209db)
如图，在pnpm dev 后面指定了host参数后，就一直报错无法使用了

**Comment by 99percentpeople** [comment]
@liujia0422 由于浏览器限制，很多API不能在非https的情况下使用，局域网部署要使用要自签名ssl证书

**Comment by dongfangbai-a** [comment]
加了自签名证书倒是能进去了，但是还是无法创建房间，ws连不上
![image](https://github.com/user-attachments/assets/edf32c53-cb2d-4096-bdff-66febb05ee4d)
![image](https://github.com/user-attachments/assets/0762b7c7-cd5e-4492-99e1-a3b1ac7c4c10)

**Comment by dongfangbai-a** [comment]
ws服务就是用的这个
![image](https://github.com/user-attachments/assets/4c46251f-969e-45e1-bced-9f935e09db0b)
![image](https://github.com/user-attachments/assets/dec50b14-53b3-4078-b058-0837b0512fda)

**Comment by 99percentpeople** [comment]
@liujia0422  你试试直接使用https://webl.ink ， websocket服务器填局域网地址，看看有没有用

**Comment by dongfangbai-a** [comment]
![image](https://github.com/user-attachments/assets/2f15c939-01ef-4f03-9bca-93599c5fb09a)
![image](https://github.com/user-attachments/assets/4091a6ad-725f-4407-8ae3-76f2a2a6de27)

试了创建不了房间，是因为本地wbelink-ws-server创建的服务没有部署证书吗

**Comment by dongfangbai-a** [comment]
我发现https://webl.ink/在PC端能够创建房间，但是手机上edge浏览器里也创建不了房间，我是指没把wsurl改成局域网地址的情况也是创建不了

**Comment by 99percentpeople** [comment]
@liujia0422 改成 ws://191.168.3.30:9000 可用吗

**Comment by dongfangbai-a** [comment]
不行，浏览器不允许使用ws,必须用wss
![image](https://github.com/user-attachments/assets/4fb1b07e-7095-4679-a91e-d5a9bf0a6b9c)

**Comment by 99percentpeople** [comment]
@liujia0422 看来服务器也需要部署证书，我会在后面的更新配置服务器部署证书

**Comment by dongfangbai-a** [comment]
好的，我刚才说了https://webl.ink/ 在手机端也用不了，只在PC端能创房间

**Comment by 99percentpeople** [comment]
@liujia0422 我已经试过可以使用手机的Chrome和Edge创建房间，如果你创建不了房间，可以截图日志信息吗

**Comment by 99percentpeople** [comment]
我已经添加对TLS的支持，可以查看[这里](https://github.com/99percentpeople/weblink-ws-server/commit/4c522d2908f7421e8538fcaa9ce91bb4880d3b5e)

**Comment by dongfangbai-a** [comment]
没有错误信息
![image](https://github.com/user-attachments/assets/333f78b6-e161-44b5-be28-3c37f9d8d7b7)

**Comment by dongfangbai-a** [comment]
错误日志在这
![image](https://github.com/user-attachments/assets/01a1e759-08e1-4c31-9a8c-660847db354b)

**Comment by 99percentpeople** [comment]
@liujia0422 无法连接服务器，由于服务器部署在香港，可能是网络运营商的原因

**Comment by dongfangbai-a** [comment]
可我是在电脑上创建房间成功之后手机扫码加入房间，PC上创房间是成功了的，而且电脑和手机是连的同一个网络

**Comment by dongfangbai-a** [comment]
确实是因为在香港的原因，检验过了

**Comment by 99percentpeople** [comment]
@liujia0422 我尝试修复了兼容性问题，现在可以在本地非安全的上下文中使用了
