### ISSUE TITLE
docker自动构建ws-server失败

### ISSUE THREAD

**Issue by feimao999** [99percentpeople/weblink#7]
truenas scale 24.10 使用dockge部署

自动构建ws-server报错

[+] Building 110.8s (14/14) FINISHED                                                      docker:default
 => [ws-server internal] load git source https://github.com/99percentpeople/weblink-ws-server.git   5.0s
 => [ws-server internal] load metadata for docker.io/oven/bun:1                                     3.8s
 => [ws-server base 1/2] FROM docker.io/oven/bun:1@sha256:e2c0b11e277f0285e089ffb77ad831faeec2833  20.4s
 => => resolve docker.io/oven/bun:1@sha256:e2c0b11e277f0285e089ffb77ad831faeec2833b9c4b04d6d317f05  0.4s
 => => sha256:e2c0b11e277f0285e089ffb77ad831faeec2833b9c4b04d6d317f054e587ef4e 1.61kB / 1.61kB      0.0s
 => => sha256:ac1ec47df7c97eb8dfc235dc9f9b9c25f42d0bfa7627c38e9322f25d5a5b08f9 1.24kB / 1.24kB      0.0s
 => => sha256:9d8f44ab69fb724cf7c8cbfc3cce1150347038f308ec23bc3dc4655f64788629 3.41kB / 3.41kB      0.0s
 => => sha256:9439c0e98e5f72dba1ea7cf303c3ca61ff9a91b26911886adb4266e2ad40bb58 55.08MB / 55.08MB    3.5s
 => => sha256:024f41e92d7e015bd13281efb09d50ae1082122dfc937b45fd64e07f29b860a7 296B / 296B          0.9s
 => => sha256:09a316be59620b26bbcdb9f1d62616eaa8f96b88b4fcc6b9567e32f5cee158d8 37.95MB / 37.95MB    4.8s
 => => sha256:5fbc0a20c406140f51033a257cb945f0b18bec0319904592d6ecda9a2d1c1956 4.15kB / 4.15kB      1.7s
 => => sha256:978ac87c47125400924208179446300f083f86cc5c943a45ae937d2d9ccc060f 139B / 139B          2.2s
 => => extracting sha256:9439c0e98e5f72dba1ea7cf303c3ca61ff9a91b26911886adb4266e2ad40bb58           2.4s
 => => extracting sha256:024f41e92d7e015bd13281efb09d50ae1082122dfc937b45fd64e07f29b860a7           0.0s
 => => extracting sha256:09a316be59620b26bbcdb9f1d62616eaa8f96b88b4fcc6b9567e32f5cee158d8           0.8s
 => => extracting sha256:5fbc0a20c406140f51033a257cb945f0b18bec0319904592d6ecda9a2d1c1956           0.0s
 => => extracting sha256:978ac87c47125400924208179446300f083f86cc5c943a45ae937d2d9ccc060f           0.0s
 => [ws-server base 2/2] WORKDIR /usr/app                                                           1.7s
 => [ws-server install 1/3] RUN mkdir -p /temp/prod                                                 4.3s
 => [ws-server install 2/3] COPY package.json bun.lockb /temp/prod/                                10.3s
 => [ws-server install 3/3] RUN cd /temp/prod && bun install --frozen-lockfile --production        11.3s
 => [ws-server prerelease 1/3] COPY --from=install /temp/prod/node_modules node_modules            10.5s
 => [ws-server prerelease 2/3] COPY . .                                                             5.3s
 => [ws-server prerelease 3/3] RUN bun run build                                                    4.9s
 => [ws-server release 1/2] COPY --from=prerelease /usr/app/dist/index.js .                         8.4s
 => [ws-server release 2/2] COPY --from=prerelease /usr/app/package.json .                          5.7s
 => [ws-server] exporting to image                                                                  0.7s
 => => exporting layers                                                                             0.6s
 => => writing image sha256:ac97920772767e5521dc6614fcd4f9f0f9aab964056bb3f6b50719bdbafe8952        0.0s
 => => naming to docker.io/library/weblink-ws-server                                                0.1s
 => [weblink internal] load build definition from Dockerfile                                        0.8s
 => => transferring dockerfile: 2B                                                                  0.0s
failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

希望可以有手动部署的方法

**Comment by 99percentpeople** [comment]
@feimao999 看起来不是构建ws-server时报错，而是在构建完服务器后没有找到当前weblink项目目录下的Dockerfile，请确定你克隆仓库的目录存在Dockerfile这个文件

**Comment by feimao999** [comment]
我是用github中的 docker-compose.yaml改的， 改了ports和volume而已,我是觉得可能是truenas scale的问题，不能运行https://github.com/99percentpeople/weblink-ws-server.git 这类脚本,说实话我也不懂怎样解决，他的意思是找不到docker file文件,那我应该如何指定Dockerfile这个文件呢？

version: "3"

services:
  weblink:
    build:
      context: .
      args:
        # Set your public websocket url here, here is an example
        VITE_WEBSOCKET_URL: ws://192.168.8.10:8080/ws
    ports:
      - "8080:80"
      - "9443:443"
    environment:
      - ENABLE_SSL=${ENABLE_SSL:-false}
    volumes:
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - ws-server

  ws-server:
    build:
      args:
        LOG_LEVEL: info
      context: https://github.com/99percentpeople/weblink-ws-server.git
    ports:
      - "9000:9000"

**Comment by feimao999** [comment]
我是用github中的 docker-compose.yaml改的， 改了ports和volume而已,我是觉得可能是truenas scale的问题，不能运行https://github.com/99percentpeople/weblink-ws-server.git 这类脚本,说实话我也不懂怎样解决，他的意思是找不到docker file文件,那我应该如何指定Dockerfile这个文件呢？

version: "3"

services:
  weblink:
    build:
      context: .
      args:
        # Set your public websocket url here, here is an example
        VITE_WEBSOCKET_URL: ws://192.168.8.10:8080/ws
    ports:
      - "8080:80"
      - "9443:443"
    environment:
      - ENABLE_SSL=${ENABLE_SSL:-false}
    volumes:
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - ws-server

  ws-server:
    build:
      args:
        LOG_LEVEL: info
      context: https://github.com/99percentpeople/weblink-ws-server.git
    ports:
      - "9000:9000"

**Comment by 99percentpeople** [comment]
不需要指定，仓库目录自带[Dockerfile](https://github.com/99percentpeople/weblink/blob/public/Dockerfile)文件，和[weblink-ws-server](https://github.com/99percentpeople/weblink-ws-server.git)没关系，检查你运行docker compse命令的目录是不是项目目录，不要把docker-compose.yaml移动到其他地方运行

**Comment by feimao999** [comment]
我弄明白了，原来是构建weblink出现问题，找不到docker file文件，想象中应该是会在当前目录自动创建dockerfile文件，但是不懂我这边为什么没有自动创建，最后我是手动下载创建并指定当前目录的weblink文件夹才成功构建镜像。我以为是和平常创建docker一样从官方拉去镜像，原来这个是要本地创建镜像。（方便问一下为什么没有上架官方镜像，这样应该就没有我这个问题了）。我试用了觉得还是很有意思的，只是这个真p2p还是感觉有点不方便，例如对方没上线就完全不能发送消息和文件，我觉得至少消息能发的话还是一些小文件可以通过服务器中转还是不错的，我原本的设想是在手机上看到某些网址可以方便发送到电脑，但是如果完全只是p2p的话就无法实现了。最后吐槽一下那个默认生成的头像是真的不行，建议改成字母还是汉字什么的比较好看些。加油

**Comment by 99percentpeople** [comment]
构建镜像时后端信令服务器链接是编译时确定的常量，我还没找到能在编译后确定的方法，后面会研究一下，然后发布到docker hub上。

我的设想是在没有连接时可以先把文件放到浏览器缓存中，在对方上线后再发送或者自己获取，目前还没没有考虑到文本信息的暂存，后面我会加上暂存文本信息的方法。

这个应用设计是尽可能少地使用服务器，而且增加这些功能会增加应用的复杂度，导致更多的bug。

目前在手机上使用，可使用小窗的方式，因为web限制，跳转到其他窗口很容易断开，头像其实是GitHub上的随机用户头像，不合适可以自己在连接前指定。
