### ISSUE TITLE
Docker构建失败【ENABLE_SSL=true docker-compose up -d】

### ISSUE THREAD

**Issue by hdu12** [99percentpeople/weblink#9]
镜像构建没问题：
root@docker02:/docker/weblink-public# ENABLE_SSL=true docker-compose up -d
Building weblink
[+] Building 120.1s (20/20) FINISHED                                                                                                                                                                   docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                             0.0s
 => => transferring dockerfile: 632B                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                                                                                                                  1.6s
 => [internal] load metadata for docker.io/library/node:20-slim                                                                                                                                                  1.5s
 => [internal] load .dockerignore                                                                                                                                                                                0.0s
 => => transferring context: 196B                                                                                                                                                                                0.0s
 => [internal] load build context                                                                                                                                                                                0.1s
 => => transferring context: 1.11MB                                                                                                                                                                              0.0s
 => CACHED [stage-3 1/5] FROM docker.io/library/nginx:alpine@sha256:74175cf34632e88c6cfe206897cbfe2d2fecf9bf033c40e7f9775a3689e8adc7                                                                             0.0s
 => [base 1/3] FROM docker.io/library/node:20-slim@sha256:a0196893dffad1f1a5723a8c817b45681402be549a8f196bf9c93a5bc30628e3                                                                                       0.0s
 => CACHED [base 2/3] WORKDIR /app                                                                                                                                                                               0.0s
 => CACHED [base 3/3] RUN npm install -g pnpm                                                                                                                                                                    0.0s
 => CACHED [install 1/3] RUN mkdir -p /temp/prod                                                                                                                                                                 0.0s
 => [install 2/3] COPY package.json pnpm-lock.yaml /temp/prod/                                                                                                                                                   2.2s
 => [install 3/3] RUN cd /temp/prod && pnpm install                                                                                                                                                             34.5s
 => [build 1/3] COPY --from=install /temp/prod/node_modules node_modules                                                                                                                                        36.5s 
 => [build 2/3] COPY . .                                                                                                                                                                                         0.4s 
 => [build 3/3] RUN pnpm build                                                                                                                                                                                  27.4s 
 => [stage-3 2/5] COPY --from=build /app/dist /usr/share/nginx/html                                                                                                                                              0.2s 
 => [stage-3 3/5] COPY docker/nginx.conf.template /etc/nginx/nginx.conf.template                                                                                                                                 0.1s 
 => [stage-3 4/5] COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh                                                                                                                                         0.6s 
 => [stage-3 5/5] RUN chmod +x /usr/local/bin/entrypoint.sh                                                                                                                                                      0.7s 
 => exporting to image                                                                                                                                                                                           1.1s 
 => => exporting layers                                                                                                                                                                                          1.0s 
 => => writing image sha256:cba25d8b5a86ab18eccae87e19ca8aad3cb346170543eea8a1772c8b7310d27c                                                                                                                     0.0s
 => => naming to docker.io/library/weblink-public_weblink                                                                                                                                                        0.0s
WARNING: Image for service weblink was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating weblink-public_ws-server_1 ... done
Creating weblink-public_weblink_1   ... done
**但是docker运行有问题**
root@docker02:/docker/weblink-public# docker ps -a
CONTAINER ID   IMAGE                      COMMAND              CREATED          STATUS                      PORTS                                       NAMES
76b8f41464de   weblink-public_weblink     "entrypoint.sh"      35 seconds ago   Exited (1) 34 seconds ago                                               weblink-public_weblink_1
51c37c9ecff1   weblink-public_ws-server   "bun run index.js"   36 seconds ago   Up 35 seconds               0.0.0.0:9000->9000/tcp, :::9000->9000/tcp   weblink-public_ws-server_1
**发现抱错在entrypoint.sh的SSL变量**
root@docker02:/docker/weblink-public# docker logs 76b8f41464de
2024/11/25 10:49:56 [emerg] 10#10: unexpected "{" in /etc/nginx/nginx.conf:43
nginx: [emerg] unexpected "{" in /etc/nginx/nginx.conf:43
有尝试修改entrypoint.sh和nginx.conf.template，但是因为checksum的问题无法构建。
尝试了使用http构建配合nginx，但是ws的SSL问题无法访问。
希望作者看一下谢谢

**Comment by hdu12** [comment]
大致检查了一下
if [ "$ENABLE_SSL" = "true" ]; then
    envsubst '${ENABLE_SSL}' </etc/nginx/nginx.conf.template >/etc/nginx/nginx.conf
这段并没有什么用，在true的时候
{% if $ENABLE_SSL == "true" %}和{% endif %}
都没有被删除导致nginx都配置报错

**Comment by hdu12** [comment]
尝试了手动删除{% if $ENABLE_SSL == "true" %}和{% endif %}
目前是起来了

**Comment by 99percentpeople** [comment]
感谢你发现问题，我会尝试解决这个问题
